#!/bin/bash

# ./lab1-check-4

# Author:  Murray Saul
# Date:    January 8, 2020
# Modified by: Jason Carman
# Date: August 30, 2024
#
# Purpose: Check that user correctly manipulated the specified directory
#          structure. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab1-check-4_output.txt

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# System information gathering
echo "OSL645 Lab 1 Check 4 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab1
echo | tee -a $logfile
echo "CHECKING YOUR LAB 1 WORK:" | tee -a $logfile

# Start checking lab
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory osl640xx/notes removed in home directory
echo -n "Checking \"osl640xx/notes\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/osl640xx/notes" "The directory pathname \"$HOME/osl640xx/notes\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/notes\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory osl640xx/tutorials removed in home directory
echo -n "Checking \"osl640xx/tutorials\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/osl640xx/tutorials" "The directory pathname \"$HOME/osl640xx/tutorials\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/tutorials\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory osl640xx/samples removed in home directory
echo -n "Checking \"osl640xx/samples\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/osl640xx/samples" "The directory pathname \"$HOME/osl640xx/samples\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/samples\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory nwk680xx created in removed directory
echo -n "Checking \"nwk680xx\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/nwk680xx" "The directory pathname \"$HOME/nwk680xx\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory nwk680xx/osl640xx removed in home directory
echo -n "Checking \"nwk680xx/osl640xx\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/nwk680xx/osl640xx" "The directory pathname \"$HOME/nwk680xx/osl640xx\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory nwk680xx/osl640xx/notes removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/notes\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/nwk680xx/osl640xx/notes" "The directory pathname \"$HOME/nwk680xx/osl640xx/notes\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/notes\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory nwk680xx/osl640xx/tutorials removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/tutorials\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/nwk680xx/osl640xx/tutorials" "The directory pathname \"$HOME/nwk680xx/osl640xx/tutorials\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/tutorials\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory nwk680xx/osl640xx/samples removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/samples\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/nwk680xx/osl640xx/samples" "The directory pathname \"$HOME/nwk680xx/osl640xx/samples\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/samples\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory nwk680xx/osl640xx/tutorials/osm620xx removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/tutorials/osm620xx\" directory has been removed in your home directory: " | tee -a $logfile
check "! test -d $HOME/nwk680xx/osl640xx/tutorials/osm620xx" "The directory pathname \"$HOME/nwk680xx/osl640xx/tutorials/osm620xx\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/tutorials/osm620xx\" in your home directory and re-run this checking script" | tee -a $logfile

warningcount=`grep -c "WARNING" $logfile`

echo | tee -a $logfile
echo | tee -a $logfile
if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 1 - Check 4." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi