#!/bin/bash

# ./lab1-check-2

# Author:  Murray Saul
# Date:    January 8, 2020
# Modified by: Jason Carman
# Date: August 31, 2024
#
# Purpose: Check that user correctly created the specified directory
#          structure. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab1b_output.txt

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is logged in as root
#if [ $(whoami) != "root" ]; then
#  echo "Note: You are required to run this program with elevated privileges.  Use sudo."
#  exit 1
#fi

# System information gathering
echo "OSL645 Lab 1B Check Script" > $logfile
echo | tee -a $logfile
echo "SYSTEM INFORMATION:" | tee -a $logfile

# Start checking lab1
echo | tee -a $logfile
echo "CHECKING YOUR LAB 1 WORK:" | tee -a $logfile

# Check that the user is created
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile
hostnamectl | tee -a $logfile
echo -n "              Date: "  | tee -a $logfile
date | tee -a $logfile

# Start checking of week2 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory osl640xx created in home directory
echo -n "Checking \"osl640xx\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/osl640xx" "The directory pathname \"$HOME/osl640xx\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory osm620xx created in home directory
echo -n "Checking \"osm620xx\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/osm620xx" "The directory pathname \"$HOME/osm620xx\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osm620xx\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory nwk680xx created in home directory
echo -n "Checking \"nwk680xx\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/nwk680xx" "The directory pathname \"$HOME/nwk680xx\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory osl640xx/notes created in home directory
echo -n "Checking \"osl640xx/notes\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/osl640xx/notes" "The directory pathname \"$HOME/osl640xx/notes\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/notes\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory osl640xx/tutorials created in home directory
echo -n "Checking \"osl640xx/tutorials\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/osl640xx/tutorials" "The directory pathname \"$HOME/osl640xx/tutorials\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/tutorials\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory osl640xx/examples created in home directory
echo -n "Checking \"osl640xx/samples\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/osl640xx/samples" "The directory pathname \"$HOME/osl640xx/samples\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/samples\" in your home directory and re-run this checking script" | tee -a $logfile

warningcount=`grep -c "WARNING" $logfile`

echo | tee -a $logfile
echo | tee -a $logfile
if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 1 - Check 2." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi
