#!/bin/bash

# lab10-check-4

# Author: Jason Carman
# Modified:	November 20, 2024
#
# Purpose: Verify that user created a shell script "convert.bash"
#          and ran it
#          
#          This script also checks to if student's script's output match the
#          required output as per tutorial instructions
#     
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status
suser=${SUDO_USER:-$USER}
logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab10-check-3_output.txt

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo "$2" 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi


# System information gathering
echo "OSL645 Lab 10 Check 4 Script" > $logfile
echo | tee -a $logfile
echo "CHECKING YOUR LAB 10 WORK:" | tee -a $logfile
echo | tee -a $logfile

# Check the createusers.bash script exists
echo -n "Checking your \"createusers.bash\" shell script file exists: " | tee -a $logfile
check "test -f $HOME/lab-10-*/createusers.bash" "The file \"createusers.bash\" does NOT exist. Use Git to clone your repo and re-run this checking script\n." | tee -a $logfile

# Check tstark user created
echo "Checking that tstark user created: " | tee -a $logfile
check "grep -isq \"tstark\" /etc/passwd" "This program did NOT detect the user \"tstark\" in the \"/etc/passwd\" file. Please execute your createusers.bash script, and re-run this checking script." | tee -a $logfile

# Check bbanner user created
echo "Checking that bbanner user created: " | tee -a $logfile
check "grep -isq \"bbanner\" /etc/passwd" "This program did NOT detect the user \"bbanner\" in the \"/etc/passwd\" file. Please execute your createusers.bash script, and re-run this checking script." | tee -a $logfile

# Check thor user created
echo "Checking that thor user created: " | tee -a $logfile
check "grep -isq \"thor\" /etc/passwd" "This program did NOT detect the user \"thor\" in the \"/etc/passwd\" file. Please execute your createusers.bash script, and re-run this checking script." | tee -a $logfile

# Check srogers user created
echo "Checking that srogers user created: " | tee -a $logfile
check "grep -isq \"srogers\" /etc/passwd" "This program did NOT detect the user \"srogers\" in the \"/etc/passwd\" file. Please execute your createusers.bash script, and re-run this checking script." | tee -a $logfile

# Check nromanoff user created
echo "Checking that nromanoff user created: " | tee -a $logfile
check "grep -isq \"nromanoff\" /etc/passwd" "This program did NOT detect the user \"nromanoff\" in the \"/etc/passwd\" file. Please execute your createusers.bash script, and re-run this checking script." | tee -a $logfile

warningcount=`grep -c "WARNING" $logfile`

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 10 - Check 4" | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi