#!/bin/bash

# ./lab1-check-1

# Author:  Murray Saul
# Date:    May 22, 2016
# Modified by: Jason Carman
# Date: August 30, 2024
#
# Purpose: Check that students correctly installed the Ubuntu VM
#          and properly performed common Linux commands. Script will
#          exit if errors, but provide feedback to correct the problem.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab1-check-1_output.txt

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo
     echo
     echo -e "\e[0;31mWARNING\e[m"
     echo
     echo
     echo $2
     echo
     exit 1
  fi

} # end of check() function

clear  # Clear the screen

# Make certain user is logged in as root
if [ $(whoami) != "root" ]; then
  echo "Note: You are required to run this program with elevated privileges.  Use sudo."
  exit 1
fi

# System information gathering
echo "OSL645 Lab 1 Check 1 Script" > $logfile
echo | tee -a $logfile
echo "SYSTEM INFORMATION:" | tee -a $logfile

# Start checking lab1
echo | tee -a $logfile
echo -e "\033[1mCHECKING YOUR WORK:\033[0m" | tee -a $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile
hostnamectl | tee -a $logfile
echo -n "              Date: "  | tee -a $logfile
date | tee -a $logfile

# Check that the user is created
echo -n "Checking that user $user was created: " | tee -a $logfile
check "echo $USER &> /dev/null" "This program did NOT detect that the user $user was created. Please create this user, and re-run this shell script." | tee -a $logfile

# Check version of Linux distribution
echo -n "Checking Correct Linux Distribution: " | tee -a $logfile
check "grep -iqs \"VERSION=.*2\" /etc/os-release && grep -iqs \"ubuntu\" /etc/os-release && grep -iqs \"lts\" /etc/os-release" " Your version of Ubuntu is incorrect. You are required to use an Ubuntu LTS version (IE 24.04). Install the correct version of Ubuntu using the link provided in the OSL645 lab instructions and re-run this shell script." | tee -a $logfile

# Checking for network connectivity
echo -n "Checking for network connectivity: " | tee -a $logfile
check "wget -qO- http://google.ca &> /dev/null" "Your internet connection doesn't seem to work. Check your network adapter settings and test by pinging google.ca. It should be successful." | tee -a $logfile

# Check if /home/user/bin directory was created
echo -n "Checking that \"/home/$user/bin\" directory was created: " | tee -a $logfile
check "test -d \"/home/$user/bin\"" "This program did NOT detect that the \"/$user/bin\" directory was created. Please create this directory, and re-run this shell script." | tee -a $logfile

warningcount=`grep -c "WARNING" $logfile`

echo | tee -a $logfile
echo | tee -a $logfile
if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 1 - Check 1." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi