#!/bin/bash

# lab10-check-3

# Author:  Murray Saul
# Date:    February 17, 2021
# Modified by:	Jason Carman
# Modified:	November 20, 2024
#
# Purpose: Verify that user created a shell script "hello" exists in
#          their home directory and has execute permissions
#          
#          This script also checks to if student's script's output match the
#          required output as per tutorial instructions
#     
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status
suser=${SUDO_USER:-$USER}
logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab10-check-3_output.txt

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     printf "$2" 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi


# System information gathering
echo "OSL645 Lab 10 Check 3 Script" > $logfile
echo | tee -a $logfile
echo "CHECKING YOUR LAB 10 WORK:" | tee -a $logfile
echo | tee -a $logfile

# Check the convert.bash script exists
echo -n "Checking your \"convert.bash\" shell script file exists: " | tee -a $logfile
check "test -f $HOME/lab-10-*/convert.bash" "The file \"convert.bash\" does NOT exist. Use Git to clone your repo and re-run this checking script\n." | tee -a $logfile

echo -n "Checking your \"githublogo.png\" file exists: " | tee -a $logfile
check "test -f $HOME/lab-10-*/githublogo.png" "The file \"githublogo.png\" does NOT exist. Run your convert.bash script on your VM." | tee -a $logfile

echo -n "Checking your \"tux.png\" file exists: " | tee -a $logfile
check "test -f $HOME/lab-10-*/tux.png" "The file \"tux.png\" does NOT exist. Run your convert.bash script on your VM." | tee -a $logfile

echo -n "Checking your \"ubuntu.png\" file exists: " | tee -a $logfile
check "test -f $HOME/lab-10-*/ubuntu.png" "The file \"ubuntu.png\" does NOT exist. Run your convert.bash script on your VM." | tee -a $logfile

warningcount=`grep -c "WARNING" $logfile`

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 10 - Check 3" | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi