#!/bin/bash

# lab3-check-4

# Author:  Murray Saul
# Date:    February 3, 2021
# Modified By: Jason Carman
# Modified: September 18, 2024
#
# Purpose: Check that user correctly set permissions for files using
#          the chmod and umask commands. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab3-check-4_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 3 Check 4 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 3 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check ~/documents/memos/memo1.txt file has rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo1.txt\" text file has \"rw-r-----\" permissions: " | tee -a $logfile
check "ls -l ~/documents/memos/memo1.txt | grep -sq \"\-rw-r\-\-\-\-\-\"" "The text file \"~/documents/memos/memo1.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos/memo1.txt) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/memos/memo2.txt file has rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo2.txt\" text file has \"rw-r-----\" permissions: " | tee -a $logfile
check "ls -l ~/documents/memos/memo2.txt | grep -sq \"\-rw-r\-\-\-\-\-\"" "The text file \"~/documents/memos/memo2.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos/memo2.txt) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/memos/memo3.txt file has rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo3.txt\" text file has \"rw-r-----\" permissions: " | tee -a $logfile
check "ls -l ~/documents/memos/memo3.txt | grep -sq \"\-rw-r\-\-\-\-\-\"" "The text file \"~/documents/memos/memo3.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos/memo3.txt) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/memos/memo1.txt file is NOT empty
echo -n "Checking \"~/documents/memos/memo1.txt\" text file is NOT empty: " | tee -a $logfile
check "test -s  ~/documents/memos/memo1.txt" "The text file \"~/documents/memos/memo1.txt\" is NOT empty which indicates that you did NOT edit the file and save editing changes to prove adding write permissions for this file allows text edting this file. Please edit this file, type a few words, then save and exit the text editor, and then re-run this checking script" | tee -a $logfile

# Check ~/shared directory exists
echo -n "Checking \"~/shared\" directory has been created: " | tee -a $logfile
check "test -d ~/shared" "The directory pathname \"~/shared\" does NOT exists. Please create this directory and re-run this checking script" | tee -a $logfile

# Check ~/shared2 directory exists
echo -n "Checking \"~/shared2\" directory has been created: " | tee -a $logfile
check "test -d ~/shared2" "The directory pathname \"~/shared2\" does NOT exists. Please create this directory and re-run this checking script" | tee -a $logfile

# Check ~/shared2 directory has rwx------ permissions
echo -n "Checking \"~/shared2\" directory has \"rwx------\" permissions: " | tee -a $logfile
check "ls -ld ~/shared2 | grep -sq \"\drwx\-\-\-\-\-\-\"" "The directory pathname \"~/shared2\" does NOT contain the permissions \"rwx------\" (use ls -ld ~/shared2) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/shared2/myfile.txt file was created
echo -n "Checking \"~/shared2/myfile.txt\" file was created: " | tee -a $logfile
check "test -f ~/shared2/myfile.txt" "The file pathname \"~/shared2/myfile.txt\" does NOT exist. Create this empty file and re-run this checking script" | tee -a $logfile

# Check ~/shared2/myfile.txt file has rwx------ permissions
echo -n "Checking \"~/shared2/myfile.txt\" file has \"rw-------\" permissions: " | tee -a $logfile
check "ls -l ~/shared2/myfile.txt | grep -sq \"\-rw\-\-\-\-\-\-\-\"" "The file pathname \"~/shared2/myfile.txt\" does NOT contain the permissions \"rw-------\" (use ls -l ~/shared2/myfile.txt) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 3 - Check 1." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi