#!/bin/bash

# lab3-check-3

# Author:  Murray Saul
# Date:    January 21, 2020
# Modified By: Jason Carman
# Modified: September 18, 2024
#
# Purpose: Check that user correctly set permissions for directories`
#          and regular files. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab3-check-3_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 3 Check 3 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 3 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check ~/clients directory has rwxr-x--- permissions
echo -n "Checking \"~/clients\" directory has \"rwxr-x---\" permissions: " | tee -a $logfile
check "ls -ld ~/clients | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/clients\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/clients) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/vendors directory has rwxr-x--- permissions
echo -n "Checking \"~/vendors\" directory has \"rwxr-x---\" permissions: " | tee -a $logfile
check "ls -ld ~/clients | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/vendors\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/vendors) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents directory has rwxr-x--- permissions
echo -n "Checking \"~/documents\" directory has \"rwxr-x---\" permissions: " | tee -a $logfile
check "ls -ld ~/documents | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/memos directory has rwxr-x--- permissions
echo -n "Checking \"~/documents/memos\" directory has \"rwxr-x---\" permissions: " | tee -a $logfile
check "ls -ld ~/documents/memos | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents/memos\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/reports directory has rwxr-x--- permissions
echo -n "Checking \"~/documents/reports\" directory has \"rwxr-x---\" permissions: " | tee -a $logfile
check "ls -ld ~/documents/reports | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents/reports\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents/reports) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/contracts directory has rwxr-x--- permissions
echo -n "Checking \"~/documents/contracts\" directory has \"rwxr-x---\" permissions: " | tee -a $logfile
check "ls -ld ~/documents/contracts | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents/contracts\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents/contracts) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/memos/memo1.txt file has -rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo1.txt\" file has \"rw-r-----\" permissions: " | tee -a $logfile
check "ls -l ~/documents/memos/memo1.txt | cut -d' ' -f1 | grep -sq '\-rw\-r\-\-\-\-\-'" "The file \"~/documents/memos/memo1.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/memos/memo2.txt file has -rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo2.txt\" file has \"rw-r-----\" permissions: " | tee -a $logfile
check "ls -l ~/documents/memos/memo2.txt | cut -d' ' -f1 | grep -sq '\-rw\-r\-\-\-\-\-'" "The file \"~/documents/memos/memo2.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

# Check ~/documents/memos/memo3.txt file has -rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo3.txt\" file has \"rw-r-----\" permissions: " | tee -a $logfile
check "ls -l ~/documents/memos/memo3.txt | cut -d' ' -f1 | grep -sq '\-rw\-r\-\-\-\-\-'" "The file \"~/documents/memos/memo3.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 3 - Check 1." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi