#!/bin/bash

# lab4-check-2

# Author:  Murray Saul
# Date:    January 17, 2021
# Modified by:	Jason Carman
# Modified: September 20, 2024
#
# Purpose: Check that user correctly removed temporary text files
#          in their ~/redirect directory. If there are errors
#          users will be provided feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab4-check-2_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 4 Check 2 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 4 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory "redirect" created in home directory
echo -n "Checking \"$HOME/redirect\" directory has been created: " | tee -a $logfile
check "test -d $HOME/redirect" "The directory pathname \"$HOME/redirect\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"uli101xx\" in your home directory and re-run this checking script" | tee -a $logfile


# Check ~/redirect/output.txt file exists
echo -n "Checking \"$HOME/redirect/output.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/output.txt" "The text file pathname \"$HOME/redirect/output.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/output2.txt file exists
echo -n "Checking \"$HOME/redirect/output2.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/output2.txt" "The text file pathname \"$HOME/redirect/output2.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/output3.txt file exists
echo -n "Checking \"$HOME/redirect/output3.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/output3.txt" "The text file pathname \"$HOME/redirect/output3.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/field5.txt file exists
echo -n "Checking \"$HOME/redirect/field5.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/field5.txt" "The text file pathname \"$HOME/redirect/field5.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/field123.txt file exists
echo -n "Checking \"$HOME/redirect/field123.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/field123.txt" "The text file pathname \"$HOME/redirect/field123.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/field15.txt file exists
echo -n "Checking \"$HOME/redirect/field15.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/field15.txt" "The text file pathname \"$HOME/redirect/field15.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/count.txt file exists
echo -n "Checking \"$HOME/redirect/count.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/count.txt" "The text file pathname \"$HOME/redirect/count.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/count1.txt file exists
echo -n "Checking \"$HOME/redirect/count1.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/count1.txt" "The text file pathname \"$HOME/redirect/count1.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/count2.txt file exists
echo -n "Checking \"$HOME/redirect/count2.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/count2.txt" "The text file pathname \"$HOME/redirect/count2.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/listing.txt file exists
echo -n "Checking \"$HOME/redirect/listing.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/listing.txt" "The text file pathname \"$HOME/redirect/listing.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/combined.txt file exists
echo -n "Checking \"$HOME/redirect/combined.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/combined.txt" "The text file pathname \"$HOME/redirect/combined.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/result.txt file exists
echo -n "Checking \"$HOME/redirect/result.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/result.txt" "The text file pathname \"$HOME/redirect/result.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/myoutput.txt file exists
echo -n "Checking \"$HOME/redirect/myoutput.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/myoutput.txt" "The text file pathname \"$HOME/redirect/myoutput.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

# Check ~/redirect/line2.txt file exists
echo -n "Checking \"$HOME/redirect/line2.txt\" text file has been removed: " | tee -a $logfile
check "! test -f $HOME/redirect/line2.txt" "The text file pathname \"$HOME/redirect/line2.txt\" still exists. Remove that temporary text file and re-run this checking script" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 4 - Check 2." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi