#!/bin/bash

# lab4-check-1

# Author:  Murray Saul
# Date:    January 21, 2020
# Modified By: Jason Carman
# Modified: September 18, 2024
#
# Purpose: Check that user correctly created the specified directory
#          structure. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab4-check-1_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi
# System information gathering
echo "OSL645 Lab 4 Check 1 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 4 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory documents created in home directory
echo -n "Checking \"documents\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/documents" "The directory pathname \"$HOME/documents\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory clients created in home directory
echo -n "Checking \"clients\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/clients" "The directory pathname \"$HOME/clients\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"clients\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory vendors created in home directory
echo -n "Checking \"vendors\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/vendors" "The directory pathname \"$HOME/vendors\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"vendors\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory documents/memos created in home directory
echo -n "Checking \"documents/memos\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/documents/memos" "The directory pathname \"$HOME/documents/memos\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents/memos\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory documents/reports created in home directory
echo -n "Checking \"documents/reports\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/documents/reports" "The directory pathname \"$HOME/documents/reports\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents/reports\" in your home directory and re-run this checking script" | tee -a $logfile

# Check directory documents/contracts created in home directory
echo -n "Checking \"documents/contracts\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/documents/contracts" "The directory pathname \"$HOME/documents/contracts\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents/contracts\" in your home directory and re-run this checking script" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 4 - Check 1." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi