#!/bin/bash

# lab5-check-2

# Author:  Murray Saul
# Date:    January 27, 2020
# Modified by:	Jason Carman
# Modified:	October 2, 2024
#
# Purpose: Check that the user copied the files correctly
#          This shell script will exit if errors, but will provide
#          feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab5-check-2_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo "OK"
  else
     echo "WARNING"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo "ERROR:"
   echo
   echo "You are NOT located in your HOME directory."
   echo "(i.e. $HOME"
   echo
   echo -n "Issue the command (without arguments)"
   echo "and confirm that you are"
   echo "currently located in your home directory with the pwd command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 5 Check 2 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 5 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory ~/local directory created
echo -n "Checking \"~/local\" directory has been created: " | tee -a $logfile
check "test -d $HOME/local" "The directory pathname \"$HOME/local\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"local\" in your home directory and re-run this checking script" | tee -a $logfile

# Check that remotely copied file ~/local/other.txt exists
echo -n "Checking that file \"~/local/other.txt\" exists: " | tee -a $logfile
check "test -f $HOME/local/other.txt" "The file pathname \"$HOME/local/other.txt\" does NOT exist. Use the scp command to properly copy this file to your home directory and re-run this checking script" | tee -a $logfile

# Check that remotely copied file ~/local/mytextfile.txt exists
echo -n "Checking that remotely copied file \"~/local/mytextfile.txt\" exists: " | tee -a $logfile
check "test -f $HOME/local/mytextfile.txt" "The file pathname \"$HOME/local/mytextfile.txt\" does NOT exist. Use the scp command to properly copy this file to the Matrix server and re-run this checking script" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 5 - Check 2." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi