#!/bin/bash

# lab5-check-1

# Author:  Murray Saul
# Date:    January 27, 2020
# Modified by:	Jason Carman
# Modified:	September 25, 2024
#
# Purpose: Check that user correctly created the specified directory
#          structure and the regular file and it's contents.
#          This shell script will exit if errors, but will provide
#          feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab5-check-1_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory


if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 5 Check 1 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 5 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory ~/local directory created
echo -n "Checking \"~/local\" directory has been created: " | tee -a $logfile
check "test -d $HOME/local" "The directory pathname \"$HOME/local\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"local\" in your home directory and re-run this checking script" | tee -a $logfile

# Check text file myfile.txt created in local directory
echo -n "Checking \"~/local/myfile.txt\" file created: " | tee -a $logfile
check "test -f $HOME/local/myfile.txt" "The file pathname \"$HOME/local/myfile.txt\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the file \"$HOME/local/myfile.txt\" in your home directory and re-run this checking script" | tee -a $logfile

cat > /tmp/myfile.$$ <<+
This is my file
It is a small file
+

# Check text file contains the correct content
echo -n "Checking \"~/local/myfile.txt\" has same contents stated in tutorial: " | tee -a $logfile
check "diff /tmp/myfile.$$ $HOME/local/myfile.txt > /dev/null 2> /dev/null" "The file \"$HOME/local/myfile.txt\" does NOT contain the exact text as instructed in the tutorial. Please edit this file to make identical to text in tutorial (make sure to press ENTER after each line), save, exit and re-run this checking script" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 5 - Check 1." | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi