#!/bin/bash

# lab6-check-2

# Author:  Murray Saul
# Date:    March 3, 2021
# Modified by:	Jason Carman
# Modified:	October 24, 2024
#
# Purpose: Verify that user created a shell scripts to demonstrate
#          command substitution and match operations
#          
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab6-check-2_output.txt

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     printf "$2"
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 6 Check 2 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 6 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check "command-substitution.bash" shell script was created in home directory
echo -n "Checking \"command-substitution.bash\" shell script file has been created: " | tee -a $logfile
check "test -f $HOME/lab-6-*/command-substitution.bash" "The file pathname \"$HOME/lab-6-*/command-substitution.bash\" does NOT exist. Check if you mispelled file name, or used uppercase letters by mistake. Use Git to clone your repo and re-run this checking script\n" | tee -a $logfile

# Check "command-substitution.bash" shell script has execute permissions
echo -n "Checking \"command-substitution.bash\" shell script file has execute permissions: " | tee -a $logfile
check "test -x $HOME/lab-6-*/command-substitution.bash" "The shell script pathname \"$HOME/lab-6-*/command-substitution.bash\" does NOT have execute permissions. Add execute permissions for the owner (user) of the \"command-substitution.bash\" shell script file using the terminal in Codespaces. Push your changes, pull them into your Ubuntu VM and re-run this checking script\n" | tee -a $logfile

# Create the temporary BENCHMARK output file of for-2.bash for comparison purposes
# Notice that the "Here Document" is used to create this file with redirection 

cat > /tmp/compare.$$ <<+

MY ACCOUNT INFORMATION:

Username: $(whoami)

Current Directory: $(pwd)

+

# Run student's shell script and store stdout to a temp file

$HOME/lab-6-*/command-substitution.bash > /tmp/student.$$

# Check student's "command-substitution.bash"" shell script has CORRECT output
# Notice that "diff" command is used to compare your shell script's output
# with CORRECT required output (i.e. comparison file)
# Notice command's output and error thrown out to "/dev/null" since
# we are only interested in TRUE or FALSE.

echo -n "Checking your \"command-substitution.bash\" shell script file produces CORRECT required output: " | tee -a $logfile
check "diff /tmp/student.$$ /tmp/compare.$$ > /dev/null 2> /dev/null" "The OUTPUT when running your Bash shell script does NOT match\nthe required specifications provided from your tutorial instructions.\n\n\e[3;4;33mYOUR SHELL SCRIPT OUTPUT (including empty lines)\e[0m\n$(cat /tmp/student.$$)\n\n\e[3;4;33mCORRECT SHELL SCRIPT OUTPUT (including empty lines)\e[0m\n$(cat /tmp/compare.$$)\n\nCAREFULLY look for differences, then make corrections to your Bash shell script\nto match CORRECT OUTPUT, save editing changes, run your script to confirm,\nand then re-run this checking script.\n\n" | tee -a $logfile


# Check "dog-years.bash" shell script was created
echo -n "Checking \"dog-years.bash\" shell script file has been created: " | tee -a $logfile
check "test -f $HOME/lab-6-*/dog-years.bash" "The file pathname \"$HOME/lab-6-*/dog-years.bash\" does NOT exist. Check if you mispelled file name, or used uppercase letters by mistake. Use Git to clone your repo and re-run this checking script\n" | tee -a $logfile

# Check "dog-years.bash" shell script (in your home directory) has execute permissions
echo -n "Checking \"dog-years.bash\" shell script file has execute permissions: " | tee -a $logfile
check "test -x $HOME/lab-6-*/dog-years.bash" "The shell script pathname \"$HOME/lab-6-*/dog-years.bash\" does NOT have execute permissions. Add execute permissions for the owner (user) of the \"dog-years.bash\" shell script file in your home directory and re-run this checking script\n" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 6 - Check 2" | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi