#!/bin/bash
#
# lab6-check-3

# Author:  Murray Saul
# Date:    January 29, 2021
# Modified by:	Jason Carman
# Modified:	October 15, 2024
#
# Purpose: Check that user correctly created persistent aliases
#          on their VM. If the errors, then the
#          checking script will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab6-check-1_output.txt

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo "$2 "
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 6 Check 1 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 6 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo
# Assign value to a variable to act as a "flag" for alias match

match=0

# Loop to read in all aliases (line-by-line)

while read line; do

   # if line matches "lh=" pattern, increase # of matches by value of 1

   if echo "$line" | grep -sq "lh="
   then
     ((match++)) 
   fi
done < "${1:-/dev/stdin}"

# Check that "lh" alias is in computer memory using the value of
# "match" variable. If match variable is NOT equal to 0 (i.e. no matches)
# then TRUE value; otherwise, FALSE value when evaluated

echo -n "Checking \"lh\" alias has been created: " | tee -a $logfile
check "alias | grep 'alias lh='" "The alias called \"lh\" does NOT exist. Issue the \"alias\" command to properly create this alias and re-run this checking script" | tee -a $logfile

# Check that "lh" alias has been added to the ~/.bashrc startup file
echo -n "Checking that \"lh\" has been added to the \"~/.bashrc\" startup file: " | tee -a $logfile
check "grep -sq 'lh\=' ~/.bashrc" "The \"$HOME/.bashrc\" startup file does NOT contain the Linux command to create the \"lh\" alias. Make corrections and re-run this checking script" | tee -a $logfile

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 6 - Check 1" | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi