#!/bin/bash

# lab7-check-1

# Author:  Murray Saul
# Date:    January 31, 2021
# Modified by:	Jason Carman
# Modified:	October 26, 2024
#
# Purpose: Check that user correctly issued some Linux commands
#          using RE on their matrix server. If the errors, then the
#          checking script will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

logfile=$(getent passwd ${SUDO_USER:-$USER} | cut -d: -f6)/Documents/lab7-check-1_output.txt

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1; then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]; then
   echo -e "\033[1mERROR:\033[0m"
   echo
   echo "You are NOT located in your HOME directory."
   echo -e "(i.e. \033[1m$HOME\033[0m )"
   echo
   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
   echo -e "and confirm that you are"
   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
   echo "and re-run this checking script."
   echo
   echo

   exit 1
fi

# System information gathering
echo "OSL645 Lab 7 Check 1 Script" > $logfile

# Add a unique identifier to the logfile
read -p "Please enter your Seneca ID (ie jmcarman): " user
echo "Unique Identifer: $(echo $user | sha256sum)" | tee -a $logfile
echo "------------------------------------" | tee -a $logfile

# Start checking lab
echo | tee -a $logfile
echo "CHECKING YOUR LAB 7 WORK:" | tee -a $logfile

echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory regexps created in home directory
echo -n "Checking \"regexps\" directory has been created in your home directory: " | tee -a $logfile
check "test -d $HOME/regexps" "The directory pathname \"$HOME/regexps\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"regexps\" in your home directory and re-run this checking script" | tee -a $logfile

# Check that numbers1.dat file was downloaded to your regexps directory
echo -n "Checking \"numbers1.dat\" file was downloaded to the \"regexps\" directory: " | tee -a $logfile
check "test -f $HOME/regexps/numbers1.dat" "The file pathname \"$HOME/regexps/numbers1.dat\" does NOT exist. Use the \"cp\" command in Investigation 1 step 23 to properly download this file and re-run this checking script" | tee -a $logfile

# Check ~/regexps/faulty.txt file exists
echo -n "Checking \"$HOME/regexps/faulty.txt\" file exists: " | tee -a $logfile
check "test -f $HOME/regexps/faulty.txt" "The text file pathname \"$HOME/regexps/faulty.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile

# Check ~/regexps/faulty.txt file contains correct results
echo -n "Checking \"$HOME/regexps/faulty.txt\" file contains correct results: " | tee -a $logfile
grep "^[0-9]*$" ~/regexps/numbers1.dat > /tmp/temp.$$
check "diff $HOME/regexps/faulty.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/regexps/faulty.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
rm /tmp/temp.$$ 2> /dev/null

# Check ~/regexps/whole.txt file exists
echo -n "Checking \"$HOME/regexps/whole.txt\" file exists: " | tee -a $logfile
check "test -f $HOME/regexps/whole.txt" "The text file pathname \"$HOME/regexps/whole.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile

# Check ~/regexps/whole.txt file contains correct results
echo -n "Checking \"$HOME/regexps/whole.txt\" file contains correct results: " | tee -a $logfile
grep "^[0-9][0-9]*$" ~/regexps/numbers1.dat > /tmp/temp.$$
check "diff $HOME/regexps/whole.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/regexps/whole.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
rm /tmp/temp.$$ 2> /dev/null

# Check ~/regexps/signed.txt file exists
echo -n "Checking \"$HOME/regexps/signed.txt\" file exists: " | tee -a $logfile
check "test -f $HOME/regexps/signed.txt" "The text file pathname \"$HOME/regexps/signed.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile

# Check ~/regexps/signed.txt file contains correct results
echo -n "Checking \"$HOME/regexps/signed.txt\" file contains correct results: " | tee -a $logfile
grep "^[+-][0-9][0-9]*$" ~/regexps/numbers1.dat > /tmp/temp.$$
check "diff $HOME/regexps/signed.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/regexps/signed.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
rm /tmp/temp.$$ 2> /dev/null

# Check ~/regexps/all.txt file exists
echo -n "Checking \"$HOME/regexps/all.txt\" file exists: " | tee -a $logfile
check "test -f $HOME/regexps/all.txt" "The text file pathname \"$HOME/regexps/all.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile

# Check ~/regexps/all.txt file contains correct results
echo -n "Checking \"$HOME/regexps/all.txt\" file contains correct results: " | tee -a $logfile
grep "^[+-]*[0-9][0-9]*$" ~/regexps/numbers1.dat > /tmp/temp.$$
check "diff $HOME/regexps/all.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/regexps/all.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script" | tee -a $logfile
rm /tmp/temp.$$ 2> /dev/null

warningcount=$(grep -c "WARNING" $logfile)

echo | tee -a $logfile
echo | tee -a $logfile

if [ $warningcount == 0 ]; then
  echo "Congratulations!" | tee -a $logfile
  echo | tee -a $logfile
  echo "You have successfully completed Lab 7 - Check 1" | tee -a $logfile
  echo "1. Show the output of this script to your OSL645 professor." | tee -a $logfile
  echo "2. A copy of this script output has been created at $logfile." | tee -a $logfile
  echo
else
  echo "Your Lab is not complete." | tee -a $logfile
  echo "Correct the warnings listed above, then run this script again." | tee -a $logfile
fi