#!/bin/bash

# t4-check-3

# Author:  Murray Saul
# Date:    January 31, 2021
# Modified by:	Jason Carman
# Modified:	December 27, 2023
#
# Purpose: Check that user correctly created temp files via tee command
#          when issuing pipeline commands. If there are errors
#          users will be provided feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the ~/redirect directory

# if [ $PWD != $HOME/redirect ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your $HOME/redirect directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo "You are NOT located in your $HOME/redirect directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -e "Issue the \033[1mcd\033[0m command to move to this directory"
#   echo -e "and confirm that you are located in that directory"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi


# Start checking of week5 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo


# Check ~/redirect/unsort.txt file exists
echo -n "Checking \"$HOME/redirect/unsort.txt\" text file exists: "
check "test -f $HOME/redirect/unsort.txt" "The text file pathname \"$HOME/redirect/unsort.txt\" does NOT exist. Re-run the Linux pipeline command correctly and re-run this checking script"

# Check ~/redirect/sort.txt file exists
echo -n "Checking \"$HOME/redirect/sort.txt\" text file exists: "
check "test -f $HOME/redirect/sort.txt" "The text file pathname \"$HOME/redirect/sort.txt\" does NOT exist. Re-run the Linux pipeline command correctly and re-run this checking script"

# Check ~/redirect/match.txt file exists
echo -n "Checking \"$HOME/redirect/match.txt\" text file exists: "
check "test -f $HOME/redirect/match.txt" "The text file pathname \"$HOME/redirect/match.txt\" does NOT exist. Re-run the Linux pipeline command correctly and re-run this checking script"

# Create temporary files

ls /bin/???? > /tmp/unsort.txt.$$
sort /tmp/unsort.txt.$$ > /tmp/sort.txt.$$
grep r /tmp/sort.txt.$$ > /tmp/match.txt.$$


# Check ~/redirect/unsort.txt file contains correct contents
echo -n "Checking \"$HOME/redirect/unsort.txt\" text file contains correct contents: "
check "diff $HOME/redirect/unsort.txt /tmp/unsort.txt.$$" "The text file pathname \"$HOME/redirect/unsort.txt\" does NOT contain the correct contents. Re-run the Linux pipeline command correctly and re-run this checking script"

# Check ~/redirect/sort.txt file contains correct contents
echo -n "Checking \"$HOME/redirect/sort.txt\" text file contains correct contents: "
check "diff $HOME/redirect/sort.txt /tmp/sort.txt.$$" "The text file pathname \"$HOME/redirect/sort.txt\" does NOT contain the correct contents. Re-run the Linux pipeline command correctly and re-run this checking script"

# Check ~/redirect/match.txt file contains correct contents
echo -n "Checking \"$HOME/redirect/match.txt\" text file contains correct contents: "
check "diff $HOME/redirect/match.txt /tmp/match.txt.$$" "The text file pathname \"$HOME/redirect/match.txt\" does NOT contain correct contents. Re-run the Linux pipeline command correctly and re-run this checking script"

# Remove temporary files

rm /tmp/unsort.txt.$$ 2> /dev/null
rm /tmp/sort.txt.$$ 2> /dev/null
rm /tmp/match.txt.$$ 2> /dev/null


. /home/jason.carman/duedates.txt

weekDueDate=$t05

src=$0

export src

/home/jason.carman/tutorials/source

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi


echo "${label}tutorial4-check-3 Check Completed for: $USER" | mail -s "${label}tutorial4-check-3 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}tutorial4-check-3 Completed for: $USER" | mail -s "${label}tutorial4-check-3 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null


if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the tutorial4-check-3 script"
   echo  "This means that you correctly issued a pipeline command using the tee utility :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the tutorial4-check-3 script"
   echo  "This means that you correctly issued a pipeline command using the tee utility :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi