#!/bin/bash

# t4-check-1

# Author:  Murray Saul
# Date:    January 17, 2021
# Modified by:	Jason Carman
# Modified:	December 27, 2023
#
# Purpose: Check that user correctly created temporary text files
#          in their ~/redirect directory. If there are errors
#          users will be provided feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the ~/redirect directory

if [ $PWD != $HOME/redirect ]
 then
  echo -e "\033[1mERROR:\033[0m"
  echo
  echo "You are NOT located in your $HOME/redirect directory."
  echo -e "(i.e. \033[1m$HOME\033[0m )"
  echo
  echo -e "Issue the \033[1mcd\033[0m command to move to this directory"
  echo -e "and confirm that you are located in that directory"
  echo "and re-run this checking script."
  echo
  echo

  exit 1
fi


# Start checking of week5 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory "redirect" created in home directory
echo -n "Checking \"$HOME/redirect\" directory has been created: "
check "test -d $HOME/redirect" "The directory pathname \"$HOME/redirect\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"uli101xx\" in your home directory and re-run this checking script"


# Check ~/redirect/output.txt file exists
echo -n "Checking \"$HOME/redirect/output.txt\" text file exists: "
check "test -f $HOME/redirect/output.txt" "The text file pathname \"$HOME/redirect/output.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/output2.txt file exists
echo -n "Checking \"$HOME/redirect/output2.txt\" text file exists: "
check "test -f $HOME/redirect/output2.txt" "The text file pathname \"$HOME/redirect/output2.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/output3.txt file exists
echo -n "Checking \"$HOME/redirect/output3.txt\" text file exists: "
check "test -f $HOME/redirect/output3.txt" "The text file pathname \"$HOME/redirect/output3.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/field5.txt file exists
echo -n "Checking \"$HOME/redirect/field5.txt\" text file exists: "
check "test -f $HOME/redirect/field5.txt" "The text file pathname \"$HOME/redirect/field5.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/field123.txt file exists
echo -n "Checking \"$HOME/redirect/field123.txt\" text file exists: "
check "test -f $HOME/redirect/field123.txt" "The text file pathname \"$HOME/redirect/field123.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/field15.txt file exists
echo -n "Checking \"$HOME/redirect/field15.txt\" text file exists: "
check "test -f $HOME/redirect/field15.txt" "The text file pathname \"$HOME/redirect/field15.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/count.txt file exists
echo -n "Checking \"$HOME/redirect/count.txt\" text file exists: "
check "test -f $HOME/redirect/count.txt" "The text file pathname \"$HOME/redirect/count.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/count1.txt file exists
echo -n "Checking \"$HOME/redirect/count1.txt\" text file exists: "
check "test -f $HOME/redirect/count1.txt" "The text file pathname \"$HOME/redirect/count1.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/count2.txt file exists
echo -n "Checking \"$HOME/redirect/count2.txt\" text file exists: "
check "test -f $HOME/redirect/count2.txt" "The text file pathname \"$HOME/redirect/count2.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/listing.txt file exists
echo -n "Checking \"$HOME/redirect/listing.txt\" text file exists: "
check "test -f $HOME/redirect/listing.txt" "The text file pathname \"$HOME/redirect/listing.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/combined.txt file exists
echo -n "Checking \"$HOME/redirect/combined.txt\" text file exists: "
check "test -f $HOME/redirect/combined.txt" "The text file pathname \"$HOME/redirect/combined.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/result.txt file exists
echo -n "Checking \"$HOME/redirect/result.txt\" text file exists: "
check "test -f $HOME/redirect/result.txt" "The text file pathname \"$HOME/redirect/result.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/myoutput.txt file exists
echo -n "Checking \"$HOME/redirect/myoutput.txt\" text file exists: "
check "test -f $HOME/redirect/myoutput.txt" "The text file pathname \"$HOME/redirect/myoutput.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"

# Check ~/redirect/line2.txt file exists
echo -n "Checking \"$HOME/redirect/line2.txt\" text file exists: "
check "test -f $HOME/redirect/line2.txt" "The text file pathname \"$HOME/redirect/line2.txt\" does NOT exist. Re-run the Linux command(s) using redirection to create this temporary text file and re-run this checking script"


. /home/jason.carman/duedates.txt

weekDueDate=$t04

src=$0

export src

/home/jason.carman/tutorials/source

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}tutorial4-check-1 Check Completed for: $USER" | mail -s "${label}tutorial4-check-1 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}tutorial4-check-1 Completed for: $USER" | mail -s "${label}tutorial4-check-1 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the tutorial4-check-1 script"
   echo  "This means that the directory $HOME/redirect has been created,"
   echo  "and that you correctly issued Linux commands using redirection"
   echo  "that have created temporary text files :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the tutorial4-check-1 script"
   echo  "This means that the directory $HOME/redirect has been created,"
   echo  "and that you correctly issued Linux commands using redirection"
   echo  "that have created temporary text files :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi