#!/bin/bash

# t8-check-1

# Author:  Murray Saul
# Date:    February 18, 2021
# Modified by:	Jason Carman
# Modified:	December 27, 2023
#
# Purpose: Check that user correctly issued sed Linux commands
#          on their matrix server. If the errors, then the
#          checking script will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.
#
# License: LGPL version 3
# Link:    https://www.gnu.org/licenses/lgpl.html
#

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi


# Start checking week11 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory "sed" created in home directory
echo -n "Checking \"sed\" directory has been created in your home directory: "
check "test -d $HOME/sed" "The directory pathname \"$HOME/sed\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"sed\" in your home directory and re-run this checking script"

# Check that data.txt file was downloaded to your "sed" directory
echo -n "Checking \"data.txt\" file was downloaded to the \"sed\" directory: "
check "test -f $HOME/sed/data.txt" "The file pathname \"$HOME/sed/data.txt\" does NOT exist. Use the \"wget\" command to properly download this file and re-run this checking script"




# Check ~/sed/sed-1.txt file exists
echo -n "Checking \"$HOME/sed/sed-1.txt\" file exists: "
check "test -f $HOME/sed/sed-1.txt" "The text file pathname \"$HOME/sed/sed-1.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-1.txt file contains correct results
echo -n "Checking \"$HOME/sed/sed-1.txt\" file contains correct results: "
sed -n 'p' $HOME/sed/data.txt > /tmp/temp.$$
check "diff $HOME/sed/sed-1.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-1.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-2.txt file exists
echo -n "Checking \"$HOME/sed/sed-2.txt\" file exists: "
check "test -f $HOME/sed/sed-2.txt" "The text file pathname \"$HOME/sed/sed-2.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-2.txt file contains correct results
echo -n "Checking \"$HOME/sed/sed-2.txt\" file contains correct results: "
sed -n '1 p' $HOME/sed/data.txt > /tmp/temp.$$
check "diff $HOME/sed/sed-2.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-2.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-3.txt file exists
echo -n "Checking \"$HOME/sed/sed-3.txt\" file exists: "
check "test -f $HOME/sed/sed-3.txt" "The text file pathname \"$HOME/sed/sed-3.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-3.txt file contains correct results
echo -n "Checking \"$HOME/sed/sed-3.txt\" file contains correct results: "
sed -n '2,5 p' $HOME/sed/data.txt  > /tmp/temp.$$
check "diff $HOME/sed/sed-3.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-3.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-4.txt file exists
echo -n "Checking \"$HOME/sed/sed-4.txt\" file exists: "
check "test -f $HOME/sed/sed-4.txt" "The text file pathname \"$HOME/sed/sed-4.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-4.txt file contains correct results
echo -n "Checking \"$HOME/sed/sed-4.txt\" file contains correct results: "
sed '2,5 s/TUTORIAL/LESSON/g' $HOME/sed/data.txt > /tmp/temp.$$
check "diff $HOME/sed/sed-4.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-4.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-5.txt file exists
echo -n "Checking \"$HOME/sed/sed-5.txt\" file exists: "
check "test -f $HOME/sed/sed-5.txt" "The text file pathname \"$HOME/sed/sed-5.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-5.txt file contains correct results
echo -n "Checking \"$HOME/sed/sed-5.txt\" file contains correct results: "
sed '11 q' $HOME/sed/data.txt > /tmp/temp.$$
check "diff $HOME/sed/sed-5.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-5.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-6.txt file exists
echo -n "Checking \"$HOME/sed/sed-6.txt\" file exists: "
check "test -f $HOME/sed/sed-6.txt" "The text file pathname \"$HOME/sed/sed-6.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-6.txt file contains correct results
echo -n "Checking \"$HOME/sed/sed-6.txt\" file contains correct results: "
sed -n '/^The/ p' $HOME/sed/data.txt > /tmp/temp.$$
check "diff $HOME/sed/sed-6.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-6.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-7.txt file exists
echo -n "Checking \"$HOME/sed/sed-7.txt\" file exists: "
check "test -f $HOME/sed/sed-7.txt" "The text file pathname \"$HOME/sed/sed-7.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-7.txt file contains correct results
echo -n "Checking \"$HOME/sed/sed-7.txt\" file contains correct results: "
sed -n '/d$/ p' $HOME/sed/data.txt > /tmp/temp.$$
check "diff $HOME/sed/sed-7.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-7.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-8.txt file exists
echo -n "Checking \"$HOME/sed/sed-8.txt\" file exists: "
check "test -f $HOME/sed/sed-8.txt" "The text file pathname \"$HOME/sed/sed-8.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"

# Check ~/sed/sed-8.txt file contains correct results
# echo -n "Checking \"$HOME/sed/sed-8.txt\" file contains correct results: "
# who | sed -n '/^[a-m]/ p'  > /tmp/temp.$$
# check "diff $HOME/sed/sed-8.txt /tmp/temp.$$ > /dev/null" "The \"$HOME/sed/sed-8.txt\" does NOT  contain the correct results from issuing the pipeline command. Reissue the correct pipeline command and re-run this checking script"
# rm /tmp/temp.$$ 2> /dev/null


# Check ~/sed/sed-9.txt file exists
echo -n "Checking \"$HOME/sed/sed-9.txt\" file exists: "
check "test -f $HOME/sed/sed-9.txt" "The text file pathname \"$HOME/sed/sed-9.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Reissue the correct pipeline command and re-run this checking script"


. /home/jason.carman/duedates.txt

weekDueDate=$t08

src=$0

export src

/home/jason.carman/tutorials/source

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}tutorial8-check-1 Check Completed for: $USER" | mail -s "${label}tutorial8-check-1 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}tutorial8-check-1 Completed for: $USER" | mail -s "${label}tutorial8-check-1 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the tutorial8-check-1 script"
   echo  "This means that you properly issued all sed Linux commands"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the tutorial8-check-1 script"
   echo  "This means that you properly issued all sed Linux commands"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi