#!/bin/bash

# week3-check-3

# Author:  Murray Saul
# Date:    January 15, 2020
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that user correctly created reqular files within
#          the specified directory structure. This shell script will 
#          exit if errors, but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory
#
#if [ $PWD != $HOME ]
# then
#  echo -e "\033[1mERROR:\033[0m"
#  echo
#  echo "You are NOT located in your HOME directory."
#  echo -e "(i.e. \033[1m$HOME\033[0m )"
#  echo
#  echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#  echo -e "and confirm that you are"
#  echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#  echo "and re-run this checking script."
#  echo
#  echo
#
#  exit 1
#fi


# Start checking week3 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check regular file tutorial3/practice/examples/abc.txt exists
echo -n "Checking \"tutorial3/practice/examples/abc.txt\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/abc.txt" "The regular file pathname \"$HOME/tutorial3/practice/examples/abc.txt\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/abc.txt\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/def.text exists
echo -n "Checking \"tutorial3/practice/examples/def.text regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/def.text" "The regular file pathname \"$HOME/tutorial3/practice/examples/def.text\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/def.text\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/hij.TxT exists
echo -n "Checking \"tutorial3/practice/examples/hij.TxT\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/hij.TxT" "The regular file pathname \"$HOME/tutorial3/practice/examples/hij.TxT does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/hij.TxT\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/1a4.txt exists
echo -n "Checking \"tutorial3/practice/examples/1a4.txt\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/1a4.txt" "The regular file pathname \"$HOME/tutorial3/practice/examples/1a4.txt\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/1a4.txt\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/123.TXT exists
echo -n "Checking \"tutorial3/practice/examples/123.TXT\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/123.TXT" "The regular file pathname \"$HOME/tutorial3/practice/examples/123.TXT\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/123.TXT\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/456.txt exists
echo -n "Checking \"tutorial3/practice/examples/456.txt\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/456.txt" "The regular file pathname \"$HOME/tutorial3/practice/examples/456.txt\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/456.txt\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/6u9.txt exists
echo -n "Checking \"tutorial3/practice/examples/6u9.txt\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/6u9.txt" "The regular file pathname \"$HOME/tutorial3/practice/examples/6u9.txt\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/6u9.txt\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/ab2.html exists
echo -n "Checking \"tutorial3/practice/examples/ab2.html\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/ab2.html" "The regular file pathname \"$HOME/tutorial3/practice/examples/ab2.html\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/ab2.html and re-run this checking script"

# Check regular file tutorial3/practice/examples/1234.txt exists
echo -n "Checking \"tutorial3/practice/examples/1234.txt\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/1234.txt" "The regular file pathname \"$HOME/tutorial3/practice/examples/1234.txt\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/1234.txt\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/abcdef.txt exists
echo -n "Checking \"tutorial3/practice/examples/abcdef.txt\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/abcdef.txt" "The regular file pathname \"$HOME/tutorial3/practice/examples/abcdef.txt\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/abcdef.txt\" and re-run this checking script"

# Check regular file tutorial3/practice/examples/abcde.txt exists
echo -n "Checking \"tutorial3/practice/examples/abcde.txt\" regular file exists: "
check "test -f $HOME/tutorial3/practice/examples/abcde.txt" "The regular file pathname \"$HOME/tutorial3/practice/examples/abcde.txt\" does NOT exist. Check if you mispelled the file name, or used uppercase letters by mistake. Use the \"touch\" command to create the regular file called \"tutorial3/practice/examples/abcde.txt\" and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t03

/home/jason.carman/.hidden/transmogrify $USER 3 3 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week3-check-3 Check Completed for: $USER" | mail -s "${label}Week3-check-3 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week3-check-3 Completed for: $USER" | mail -s "${label}Week3-check-3 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week3-check-3 script"
   echo  "This means that you properly created text files in your directory :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week3-check-3 script"
   echo  "This means that you properly created text files in your directory :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi