#!/bin/bash

# week8-check-2

# Author:  Murray Saul
# Date:    January 29, 2021
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that user correctly created symbolic links
#          on their matrix server. If the errors, then the
#          checking script will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi

# Start checking week8 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory links2 created in home directory
echo -n "Checking \"links2\" directory has been created in your home directory: "
check "test -d $HOME/links2" "The directory pathname \"$HOME/links2\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"links2\" in your home directory and re-run this checking script"

# Check ~/links2/text-file.txt exists
echo -n "Checking \"$HOME/links2/text-file.txt\" file exists: "
check "test -f $HOME/links2/text-file.txt" "The text file pathname \"$HOME/links2/text-file.txt\" does NOT exist. Check if you mispelled file pathname, or used uppercase letters by mistake. Create the file \"$HOME/links2/text-file.txt\" file and re-run this checking script"

# Check ~/links2/text-file.sym.lnk exists
echo -n "Checking \"$HOME/links2/text-file.sym.lnk\" file exists: "
check "test -f $HOME/links2/text-file.sym.lnk" "The text file pathname \"$HOME/links2/text-file.sym.lnk\" does NOT exist. Check if you mispelled file pathname, used uppercase letters by mistake, or didn't properly issue the \"ln\" command with the filenames in the correct argument order. Reissue the \"ln\" command with the correct file pathnames (in the correct order)file and re-run this checking script"

# Check ~/text-file.sym.lnk exists
echo -n "Checking \"$HOME/text-file.sym.lnk\" file exists: "
check "test -f $HOME/text-file.sym.lnk" "The text file pathname \"$HOME/text-file.sym.lnk\" does NOT exist. Check if you mispelled file pathname, used uppercase letters by mistake, or didn't properly issue the \"ln\" command with the filenames in the correct argument order. Reissue the \"ln\" command with the correct file pathnames (in the correct order)file and re-run this checking script"

# Check ~/links2/text-file.sym.lnk is a symbolic link
echo -n "Checking \"$HOME/links2/text-file.sym.lnk\" file is a symbolic link: "
check "test -h $HOME/links2/text-file.sym.lnk" "The file pathname \"$HOME/links2/text-file.sym.lnk\" is NOT a symbolic link. Remove this file, reissue the \"ln\" command with the \"-s\" option and correct filename argument order and re-run this checking script"

# Check ~/text-file.sym.lnk is a symbolic link
echo -n "Checking \"$HOME/text-file.sym.lnk\" file is a symbolic link: "
check "test -h $HOME/text-file.sym.lnk" "The file pathname \"$HOME/text-file.sym.lnk\" is NOT a symbolic link. Remove this file, reissue the \"ln\" command with the \"-s\" option and correct filename argument order and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t08

/home/jason.carman/.hidden/transmogrify $USER 8 2 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week8-check-2 Check Completed for: $USER" | mail -s "${label}Week8-check-2 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week8-check-2 Completed for: $USER" | mail -s "${label}Week8-check-2 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week8-check-2 script"
   echo  "This means that you properly created the symbolic links :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week8-check-2 script"
   echo  "This means that you properly created the symbolic links :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi