#!/bin/bash

# week4-check-3

# Author:  Murray Saul
# Date:    January 21, 2020
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that user correctly set permissions for directories`
#          and regular files. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi


# Start checking of week4 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

### To be completed in future - check for file permissions set correctly ###

# Check ~/clients directory has rwxr-x--- permissions
echo -n "Checking \"~/clients\" directory has \"rwxr-x---\" permissions: "
check "ls -ld ~/clients | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/clients\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/clients) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/vendors directory has rwxr-x--- permissions
echo -n "Checking \"~/vendors\" directory has \"rwxr-x---\" permissions: "
check "ls -ld ~/clients | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/vendors\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/vendors) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/documents directory has rwxr-x--- permissions
echo -n "Checking \"~/documents\" directory has \"rwxr-x---\" permissions: "
check "ls -ld ~/documents | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/documents/memos directory has rwxr-x--- permissions
echo -n "Checking \"~/documents/memos\" directory has \"rwxr-x---\" permissions: "
check "ls -ld ~/documents/memos | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents/memos\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/documents/reports directory has rwxr-x--- permissions
echo -n "Checking \"~/documents/reports\" directory has \"rwxr-x---\" permissions: "
check "ls -ld ~/documents/reports | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents/reports\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents/reports) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/documents/contracts directory has rwxr-x--- permissions
echo -n "Checking \"~/documents/contracts\" directory has \"rwxr-x---\" permissions: "
check "ls -ld ~/documents/contracts | cut -d\" \" -f1 | grep -sq \"drwxr-x---\"" "The directory pathname \"~/documents/contracts\" does NOT contain the permissions \"rwxr-x---\" (use ls -ld ~/documents/contracts) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/documents/memos/memo1.txt file has -rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo1.txt\" file has \"rw-r-----\" permissions: "
check "ls -l ~/documents/memos/memo1.txt | cut -d' ' -f1 | grep -sq '\-rw\-r\-\-\-\-\-'" "The file \"~/documents/memos/memo1.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/documents/memos/memo2.txt file has -rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo2.txt\" file has \"rw-r-----\" permissions: "
check "ls -l ~/documents/memos/memo2.txt | cut -d' ' -f1 | grep -sq '\-rw\-r\-\-\-\-\-'" "The file \"~/documents/memos/memo2.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

# Check ~/documents/memos/memo3.txt file has -rw-r----- permissions
echo -n "Checking \"~/documents/memos/memo3.txt\" file has \"rw-r-----\" permissions: "
check "ls -l ~/documents/memos/memo3.txt | cut -d' ' -f1 | grep -sq '\-rw\-r\-\-\-\-\-'" "The file \"~/documents/memos/memo3.txt\" does NOT contain the permissions \"-rw-r-----\" (use ls -l ~/documents/memos) command to confirm. Re-issue the \"chmod\" command correctly for this directory and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t04

/home/jason.carman/.hidden/transmogrify $USER 4 3 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week4-check-3 Check Completed for: $USER" | mail -s "${label}Week4-check-3 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week4-check-3 Completed for: $USER" | mail -s "${label}Week4-check-3 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week4-check-3 script"
   echo  "This means that you correctly assigned permissions :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week4-check-3 script"
   echo  "This means that you correctly assigned permissions :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi