#!/bin/bash

# week2-check-3

# Author:  Murray Saul
# Date:    January 8, 2020
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that user correctly manipulated the specified directory
#          structure. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

if [ $PWD != $HOME ]
 then
  echo -e "\033[1mERROR:\033[0m"
  echo
  echo "You are NOT located in your HOME directory."
  echo -e "(i.e. \033[1m$HOME\033[0m )"
  echo
  echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
  echo -e "and confirm that you are"
  echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
  echo "and re-run this checking script."
  echo
  echo

  exit 1
fi


# Start checking week2 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory osl640xx/notes removed in home directory
echo -n "Checking \"osl640xx/notes\" directory has been removed in your home directory: "
check "! test -d $HOME/osl640xx/notes" "The directory pathname \"$HOME/osl640xx/notes\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/notes\" in your home directory and re-run this checking script"

# Check directory osl640xx/tutorials removed in home directory
echo -n "Checking \"osl640xx/tutorials\" directory has been removed in your home directory: "
check "! test -d $HOME/osl640xx/tutorials" "The directory pathname \"$HOME/osl640xx/tutorials\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/tutorials\" in your home directory and re-run this checking script"

# Check directory osl640xx/samples removed in home directory
echo -n "Checking \"osl640xx/samples\" directory has been removed in your home directory: "
check "! test -d $HOME/osl640xx/samples" "The directory pathname \"$HOME/osl640xx/samples\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"osl640xx/samples\" in your home directory and re-run this checking script"

# Check directory nwk680xx created in removed directory
echo -n "Checking \"nwk680xx\" directory has been removed in your home directory: "
check "! test -d $HOME/nwk680xx" "The directory pathname \"$HOME/nwk680xx\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx\" in your home directory and re-run this checking script"

# Check directory nwk680xx/osl640xx removed in home directory
echo -n "Checking \"nwk680xx/osl640xx\" directory has been removed in your home directory: "
check "! test -d $HOME/nwk680xx/osl640xx" "The directory pathname \"$HOME/nwk680xx/osl640xx\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx\" in your home directory and re-run this checking script"

# Check directory nwk680xx/osl640xx/notes removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/notes\" directory has been removed in your home directory: "
check "! test -d $HOME/nwk680xx/osl640xx/notes" "The directory pathname \"$HOME/nwk680xx/osl640xx/notes\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/notes\" in your home directory and re-run this checking script"

# Check directory nwk680xx/osl640xx/tutorials removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/tutorials\" directory has been removed in your home directory: "
check "! test -d $HOME/nwk680xx/osl640xx/tutorials" "The directory pathname \"$HOME/nwk680xx/osl640xx/tutorials\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/tutorials\" in your home directory and re-run this checking script"

# Check directory nwk680xx/osl640xx/samples removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/samples\" directory has been removed in your home directory: "
check "! test -d $HOME/nwk680xx/osl640xx/samples" "The directory pathname \"$HOME/nwk680xx/osl640xx/samples\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/samples\" in your home directory and re-run this checking script"

# Check directory nwk680xx/osl640xx/tutorials/osm620xx removed in home directory
echo -n "Checking \"nwk680xx/osl640xx/tutorials/osm620xx\" directory has been removed in your home directory: "
check "! test -d $HOME/nwk680xx/osl640xx/tutorials/osm620xx" "The directory pathname \"$HOME/nwk680xx/osl640xx/tutorials/osm620xx\" still exists. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"nwk680xx/osl640xx/tutorials/osm620xx\" in your home directory and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t02

/home/jason.carman/.hidden/transmogrify $USER 2 3 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week2-check-3 Check Completed for: $USER" | mail -s "${label}Week2-check-3 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week2-check-3 Completed for: $USER" | mail -s "${label}Week2-check-3 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week2-check-3 script"
   echo  "This means that your directory structure has been correctly removed :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week2-check-3 script"
   echo  "This means that your directory structure has been correctly removed :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi