#!/bin/bash

# week7-check-1

# Author:  Murray Saul
# Date:    Feb 10, 2021
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that user correctly created the correct file (and contents)
#          This shell script will exit if errors, but will provide
#          feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi

# Start checking week7 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory ~/myvm.txt text file was created
echo -n "Checking \"~/myvm.txt\" text file has been created: "
check "test -f $HOME/myvm.txt" "The file pathname \"$HOME/myvm.txt\" does NOT exist. Check if you mispelled file name, or used uppercase letters by mistake. Create the file \"myvm.txt\" in your home directory and re-run this checking script"

cat > /tmp/data.$$ <<+
This is line 1
This is line 2
This is line 3
+

# Check text file ~/myvm.txt contains the correct content
echo -n "Checking \"~/myvm.txt\" has same contents stated in tutorial: "
check "diff /tmp/data.$$ $HOME/myvm.txt > /dev/null 2> /dev/null" "The text file \"$HOME/myvm.txt\" does NOT contain the exact text as instructed in the tutorial. Please edit this file to make identical to text in tutorial (make sure to press ENTER after each line), save, exit and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t07

/home/jason.carman/.hidden/transmogrify $USER 7 1 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week7-check-1 Check Completed for: $USER" | mail -s "${label}Week7-check-1 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week7-check-1 Completed for: $USER" | mail -s "${label}Week7-check-1 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week7-check-1 script"
   echo  "This means that your text file has been correctly created :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week7-check-1 script"
   echo  "This means that your text file has been correctly created :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi