#!/bin/bash

# week4-check-1

# Author:  Murray Saul
# Date:    January 21, 2020
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that user correctly created the specified directory
#          structure. This shell script will exit if errors,
#          but will provide feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi

# Start checking of week2 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory documents created in home directory
echo -n "Checking \"documents\" directory has been created in your home directory: "
check "test -d $HOME/documents" "The directory pathname \"$HOME/documents\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents\" in your home directory and re-run this checking script"

# Check directory clients created in home directory
echo -n "Checking \"clients\" directory has been created in your home directory: "
check "test -d $HOME/clients" "The directory pathname \"$HOME/clients\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"clients\" in your home directory and re-run this checking script"

# Check directory vendors created in home directory
echo -n "Checking \"vendors\" directory has been created in your home directory: "
check "test -d $HOME/vendors" "The directory pathname \"$HOME/vendors\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"vendors\" in your home directory and re-run this checking script"

# Check directory documents/memos created in home directory
echo -n "Checking \"documents/memos\" directory has been created in your home directory: "
check "test -d $HOME/documents/memos" "The directory pathname \"$HOME/documents/memos\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents/memos\" in your home directory and re-run this checking script"

# Check directory documents/reports created in home directory
echo -n "Checking \"documents/reports\" directory has been created in your home directory: "
check "test -d $HOME/documents/reports" "The directory pathname \"$HOME/documents/reports\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents/reports\" in your home directory and re-run this checking script"

# Check directory documents/contracts created in home directory
echo -n "Checking \"documents/contracts\" directory has been created in your home directory: "
check "test -d $HOME/documents/contracts" "The directory pathname \"$HOME/documents/contracts\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"documents/contracts\" in your home directory and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t04

/home/jason.carman/.hidden/transmogrify $USER 4 1 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week4-check-1 Check Completed for: $USER" | mail -s "${label}Week4-check-1 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week4-check-1 Completed for: $USER" | mail -s "${label}Week4-check-1 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week4-check-1 script"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week4-check-1 script"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL IF YOUR"
   echo  "OSL640 PROFESSOR ARE GRADING TUTORIALS"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi