#!/bin/bash

# week6-check-3

# Author:  Murray Saul
# Date:    January 28, 2020
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that the user transferred the files correctly
#          This shell script will exit if errors, but will provide
#          feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo  "OK"
  else
     echo  "WARNING"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi


# Start checking week6 tutorial
echo  "CHECKING YOUR WORK:"
echo

# Check that transferred file ~/remote2/thefile.txt exists
echo -n "Checking that transferred file \"~/remote2/thefile.txt\" exists: "
check "test -f $HOME/remote2/thefile.txt" "The file pathname \"$HOME/remote2/thefile.txt\" does NOT exist. Use the sftp command to properly copy this file to the \"~/remote2\" directory and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t06

/home/jason.carman/.hidden/transmogrify $USER 6 3 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week6-check-3 Check Completed for: $USER" | mail -s "${label}Week6-check-3 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week6-check-3 Completed for: $USER" | mail -s "${label}Week6-check-3 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week6-check-3 script"
   echo  "This means that you transferred those files correctly :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week6-check-3 script"
   echo  "This means that you transferred those files correctly :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi