#!/bin/bash

# week6-check-2

# Author:  Murray Saul
# Date:    January 27, 2020
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that the user copied the files correctly
#          This shell script will exit if errors, but will provide
#          feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo "OK"
  else
     echo "WARNING"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo "ERROR:"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo "(i.e. $HOME"
#   echo
#   echo -n "Issue the command (without arguments)"
#   echo "and confirm that you are"
#   echo "currently located in your home directory with the pwd command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi

# Start checking week6 tutorial
echo  "CHECKING YOUR WORK:"
echo

# Check directory ~/remote directory created
echo -n "Checking \"~/remote\" directory has been created: "
check "test -d $HOME/remote" "The directory pathname \"$HOME/remote\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"remote\" in your home directory and re-run this checking script"

# Check that remotely copied file ~/other.txt exists
echo -n "Checking that remotely copied file \"~/other.txt\" exists: "
check "test -f $HOME/other.txt" "The file pathname \"$HOME/other.txt\" does NOT exist. Use the scp command to properly copy this file to your home directory and re-run this checking script"

# Check that remotely copied file ~/mytextfile.txt exists
echo -n "Checking that remotely copied file \"~/mytextfile.txt\" exists: "
check "test -f $HOME/mytextfile.txt" "The file pathname \"$HOME/mytextfile.txt\" does NOT exist. Use the scp command to properly copy this file to the Matrix server and re-run this checking script"

# Check that remotely copied file ~/remote/different.txt exists
echo -n "Checking that remotely copied file \"~/remote/different.txt\" exists: "
check "test -f $HOME/remote/different.txt" "The file pathname \"$HOME/remote/different.txt\" does NOT exist. Use the scp command to properly copy this file to the ~/remote directory as a different filename and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t06

/home/jason.carman/.hidden/transmogrify $USER 6 2 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week6-check-2 Check Completed for: $USER" | mail -s "${label}Week6-check-2 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week6-check-2 Completed for: $USER" | mail -s "${label}Week6-check-2 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week6-check-2 script"
   echo  "This means that you properly copied that file from your"
   echo  "local computer to your remote Linux server."
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week6-check-2 script"
   echo  "This means that you properly copied that file from your"
   echo  "local computer to your remote Linux server."
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi