#!/bin/bash

# week6-check-1

# Author:  Murray Saul
# Date:    January 27, 2020
# Modified By: Jason Carman
# Modified: January 3, 2023
#
# Purpose: Check that user correctly created the specified directory
#          structure and the regular file and it's contents.
#          This shell script will exit if errors, but will provide
#          feedback to correct the problem.
#          If no errors, then a congratulatory message will be displayed
#          so that the user can proceed to the next section.

# Function to indicate OK (in green) if check is true; otherwise, indicate
# WARNING (in red) if check is false and end with false exit status

function check(){

  if eval $1
  then
     echo -e "\e[0;32mOK\e[m"
  else
     echo -e "\e[0;31mWARNING\e[m"
     echo 
     echo $2 
     echo
     exit 1
  fi

} # end of check() function

# Set shell shell history
HISTFILE=~/.bash_history
set -o history

clear  # Clear the screen

# Make certain user is in the home directory

# if [ $PWD != $HOME ]
#  then
#   echo -e "\033[1mERROR:\033[0m"
#   echo
#   echo "You are NOT located in your HOME directory."
#   echo -e "(i.e. \033[1m$HOME\033[0m )"
#   echo
#   echo -en "Issue the \033[1mcd\033[0m command (without arguments)"
#   echo -e "and confirm that you are"
#   echo -e "currently located in your home directory with the \033[1mpwd\033[0m command,"
#   echo "and re-run this checking script."
#   echo
#   echo
# 
#   exit 1
# fi

# Start checking week6 tutorial
echo -e "\033[1mCHECKING YOUR WORK:\033[0m"
echo

# Check directory ~/remote directory created
echo -n "Checking \"~/remote\" directory has been created: "
check "test -d $HOME/remote" "The directory pathname \"$HOME/remote\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the directory \"remote\" in your home directory and re-run this checking script"

# Check text file myfile.txt created in remote directory
echo -n "Checking \"~/remote/myfile.txt\" file created: "
check "test -f $HOME/remote/myfile.txt" "The file pathname \"$HOME/remote/myfile.txt\" does NOT exist. Check if you mispelled directory name, or used uppercase letters by mistake. Create the file \"$HOME/remote/myfile.txt\" in your home directory and re-run this checking script"

cat > /tmp/myfile.$$ <<+
This is my file
It is a small file
+

# Check text file contains the correct content
echo -n "Checking \"~/remote/myfile.txt\" has same contents stated in tutorial: "
check "diff /tmp/myfile.$$ $HOME/remote/myfile.txt > /dev/null 2> /dev/null" "The file \"$HOME/remote/myfile.txt\" does NOT contain the exact text as instructed in the tutorial. Please edit this file to make identical to text in tutorial (make sure to press ENTER after each line), save, exit and re-run this checking script"

. /home/osl640/duedates.txt

weekDueDate=$t06

/home/jason.carman/.hidden/transmogrify $USER 6 1 $(date +%s)

if [ $(date +%s) -le $weekDueDate ]
then
   label=""
else
   label="LATE "
fi

echo "${label}Week6-check-1 Check Completed for: $USER" | mail -s "${label}Week6-check-1 Successfully Completed" $USER@myseneca.ca  2> /dev/null
echo "${label}Week6-check-1 Completed for: $USER" | mail -s "${label}Week6-check-1 Successfully Completed" $USER@senecapolytechnic.ca  2> /dev/null

if [ $(date +%s) -le $weekDueDate ]
then
   echo
   echo "Congratulations!"
   echo
   echo  "You have passed the week6-check-1 script"
   echo  "This means that your directory & text file have been correctly made :)"
   echo
   echo  "An email has been sent to your Seneca Polytechnic email account"
   echo  "for confirmation, keep this email for proof until the end of"
   echo  "this semester."
   echo
   echo  "You can proceed with this tutorial."
   echo
else
   echo
   echo  "You have passed the week6-check-1 script"
   echo  "This means that your directory & text file have been correctly made :)"
   echo
   echo  "UNFORTUNATELY, THE DUE DATE FOR THIS TUTORIAL HAS PASSED"
   echo  "SO YOU CANNOT RECEIVE MARKS FOR THIS TUTORIAL"
   echo
   echo  "An email of your LATE submission has been sent to your"
   echo  "Seneca Polytechnic email account"
   echo
   echo  "You can proceed with this tutorial."
   echo
fi